### ISSUE TITLE
"network create"-command crashes

### ISSUE THREAD

**Issue by oyvindhagberg** [unioslo/mreg#425]
Running locally with SQLite, empty database:
```
mreg> network create -network 10.1.0.0/16 -desc "lol"

Internal Server Error: /api/v1/networks/
Traceback (most recent call last):
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: near "&": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/mreg/mreg-master/mreg/api/v1/views.py", line 757, in post
    error = _overlap_check(request.data['network'])
  File "/opt/mreg/mreg-master/mreg/api/v1/views.py", line 729, in _overlap_check
    if overlap:
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 291, in __bool__
    self._fetch_all()
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django_logging/cursor_wrapper.py", line 12, in execute
    return self.log_query(super(CursorLogWrapper, self).execute, sql, params)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django_logging/cursor_wrapper.py", line 20, in log_query
    return method(*args)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/mreg/mreg-master/venv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: near "&": syntax error
```

**Comment by paalbra** [comment]
Why SQLite? Aren't we using Postgres specific features for IP?

**Comment by paalbra** [comment]
I would assume that this import also fails with non-postgres:

https://github.com/unioslo/mreg/blob/c2dfa0494a6ff938c4b161bb862084769fedbe50/mreg/models.py#L7

**Comment by paalbra** [comment]
If you want to run a local test instance you probably want to follow:

https://github.com/unioslo/mreg/blob/master/local-docker-psql.MD
