### ISSUE TITLE
mreg/mreg-cli crash on ipv6 network with excluded range

### ISSUE THREAD

**Issue by adobloug** [unioslo/mreg#435]
How to reproduce:

mreg> network info 2001:DB8:BAD:BAD::/64
Network:                 2001:DB8:BAD:BAD::/64
Netmask:                 ffff:ffff:ffff:ffff:0000:0000:0000:0000
Description:             some-network
Category:                
Location:                
VLAN                     666
DNS delegated:           False
Frozen                   False
IP-range:                2001:DB8:BAD:BAD:: - 2001:DB8:BAD:BAD:ffff:ffff:ffff:ffff
Reserved host addresses: 3
                         2001:DB8:BAD:BAD:: (net)
                         2001:DB8:BAD:BAD::1
                         2001:DB8:BAD:BAD::2
                         2001:DB8:BAD:BAD::3
Used addresses:          1
Unused addresses:        18446744073709551612 (excluding reserved adr.)
mreg> network add_excluded_range  2001:DB8:BAD:BAD::/64 2001:DB8:BAD:BAD::1:0 
2001:DB8:BAD:BAD:ffff:ffff:ffff:ffff                                           
OK: : Added exclude range to 2001:DB8:BAD:BAD::/64
mreg> network info  2001:DB8:BAD:BAD::/64                                      

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 971, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 833, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 590, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mreg.uio.no', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mreg-cli", line 11, in <module>
    load_entry_point('mreg-cli==0.0.0', 'console_scripts', 'mreg-cli')()
  File "/usr/lib/python3.6/site-packages/mreg_cli/main.py", line 186, in main
    cli.parse(shlex.split(line))
  File "/usr/lib/python3.6/site-packages/mreg_cli/cli.py", line 122, in parse
    args.func(args)
  File "/usr/lib/python3.6/site-packages/mreg_cli/network.py", line 171, in info
    unused = get_network_unused_count(ip_range)
  File "/usr/lib/python3.6/site-packages/mreg_cli/util.py", line 486, in get_network_unused_count
    return get(path).json()
  File "/usr/lib/python3.6/site-packages/mreg_cli/util.py", line 304, in get
    return _request_wrapper("get", path, params=params, ok404=ok404)
  File "/usr/lib/python3.6/site-packages/mreg_cli/util.py", line 287, in _request_wrapper
    result = getattr(session, type)(url, params=params, data=data, timeout=HTTP_TIMEOUT)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 651, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mreg.uio.no', port=443): Read timed out. (read timeout=20)

**Comment by oyvindkolbu** [comment]
This is to blame: https://github.com/unioslo/mreg/blob/53abcdabe0c1886f4c19c34776d9cebe1d4d531d/mreg/models.py#L526-L531, which basically takes forever in the example above as the exclude range contains 18446744073709486079 ipaddresses.

**Comment by adobloug** [comment]
you should be able to calculate the unusable ipv6 addresses by a substraction:
>>> a=0x20010db80bad0bad0000000000010000
>>> b=0x20010db80bad0badffffffffffffffff
>>> b-a
18446744073709486079

**Comment by oyvindkolbu** [comment]
Yes, some smarter code to check if ip in in a exclude range and perform arithmetic to get the count would be better.
